update

diff --git a/.github/workflows/Android.yml b/.github/workflows/Android.yml
--- a/.github/workflows/Android.yml
+++ b/.github/workflows/Android.yml
@@ -18,23 +18,8 @@ jobs:
         # Add the Android SDK command-line tools to the PATH
         export PATH="$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"
         
-        # List available system images (optional but useful for debugging)
-        #sdkmanager --list | grep "system-images"
-
         sdkmanager "system-images;android-35;google_apis_playstore;x86_64"
-
-        echo "ls emulator"
-        ls -l $ANDROID_SDK_ROOT/emulator
-        echo "ls cmdline-tools"
-        ls -l $ANDROID_SDK_ROOT/cmdline-tools/latest/bin
-
-        # Optionally, verify that avdmanager is now available:
-        which avdmanager
-        which emulator || { echo "Emulator binary not found"; exit 1; }
-
-        # Ensure the directory exists
-        ls -l $ANDROID_SDK_ROOT/system-images/android-35/google_apis_playstore/x86_64
-
+        
         # Create an AVD named "test" using the specified system image
         echo "no" | avdmanager create avd -n test -k "system-images;android-35;google_apis_playstore;x86_64" --force
         
@@ -58,11 +43,21 @@ jobs:
         adb shell input keyevent 82
 
         
-    # - name: Enable KVM
-    #   run: |
-    #     echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
-    #     sudo udevadm control --reload-rules
-    #     sudo udevadm trigger --name-match=kvm
+    # List available system images (optional but useful for debugging)
+    # sdkmanager --list | grep "system-images"
+
+    # echo "ls emulator"
+    # ls -l $ANDROID_SDK_ROOT/emulator
+    # echo "ls cmdline-tools"
+    # ls -l $ANDROID_SDK_ROOT/cmdline-tools/latest/bin
+
+    # # Optionally, verify that avdmanager is now available:
+    # which avdmanager
+    # which emulator || { echo "Emulator binary not found"; exit 1; }
+
+    # Ensure the directory exists
+    # ls -l $ANDROID_SDK_ROOT/system-images/android-35/google_apis_playstore/x86_64
+
 
     # - name: run tests
     #   uses: reactivecircus/android-emulator-runner@v2
